---
title: " " #replace the title with something short and catchy to represent your project
subtitle: "____'s Data Science Portfolio" #replace blank with your name
output:
  html_document:
    df_print: paged
---

## Abstract

In under 250 words give a brief summary of the project so far.

### 1. Discovery and Data Preparation

Cleaning and preprocessing the census data, using some visualizations conducting prelim analysis of predictor variables. [p01](Deliverables/p01DiscoveryAndDataPrep.html)

### 2. Model Planning and Building

Planning the model, exploratory data analysis and investigation of the predictor variables and their relationship with the response variable `income`. [p02](Deliverables/P02ModelPlanningandBuilding.html)

### 3. Results and Operationalization

Covariant analysis and fitting a logistic regression model to predict `income` based on some carefully chosen
predictor variables. A short discussion about operationalization and ethical concerns. [P03](Deliverables/P03ResultsandOperationalization.html)

Coming soon...

